name: test-secret

on:
  push:
    branches:
      - "test-secret"


jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gnupg
      
      - name: Decode secret
        env: 
          KEY: ${{ secrets.IMPORT_PROFILE_KEY }}
          FILE: use-parallel-server-in-actions/GithubActionTest.settings
        run: |
          .github/secrets-management/decrypt-in-github.sh ${KEY} ${FILE}
          cat ${FILE}

      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-beta
        with: 
          release: R2023a
          products: |
            Parallel_Computing_Toolbox

      # Runs a set of commands using the runners shell
      - name: Check MATLAB Install
        uses: matlab-actions/run-command@v1
        with:
          command: "cd use-parallel-server-in-actions; runme"
          