name: test-secret

on:
  push:
    branches:
      - "test-secret"


jobs:
  build:
    runs-on: ubuntu-latest
  
  steps:
    - uses: actions/checkout@v2

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: gnupg
    
    - name: Decode secret
      env: 
        KEY: ${{ secrets.FILE_TO_IGNORE_KEY }}
      run: |
        cd use-parallel-server-in-actions
        ./scripts/decrypt-in-github ${KEY} file-to-ignore
        cat file-to-ignore